# Rest-client stöder .env
#@API_URL = {{$dotenv PRODUCTION_API}}
@API_URL = http://localhost:3000


@DEV_TOKEN = {{$dotenv DEV_TOKEN}}

GET {{API_URL}}/login


###endpoint för att hämta en specifik note
GET {{API_URL}}/login/6f128bb3-9111-44e1-9e2a-194d272d8af1

### logga in
POST {{API_URL}}/login
Content-Type: application/json

{
   "username": "Albin",
   "password_hash": "password123"
}

### Skapa ny note
POST {{API_URL}}/register
Content-Type: application/json

{
   "username": "Herssso",
   "password_hash": "password123",
   "role": "user",
   "email": "hero@example.com"

}

### Uppdatera note
PUT {{API_URL}}/login/4
Content-Type: application/json

{
    "note": "Ny text!!"
}

### Uppdatera note
DELETE {{API_URL}}/login/