# Rest-client stöder .env
#@API_URL = {{$dotenv PRODUCTION_API}}
@API_URL = http://localhost:3000
GET {{API_URL}}/login

### Skapa ny note
POST {{API_URL}}/register
Content-Type: application/json

{
   "username": "Frissppe",
   "password_hash": "Dettaärddettlösenord",
   "role": "admin"

}

### Uppdatera note
PUT {{API_URL}}/login/4
Content-Type: application/json

{
    "note": "Ny text!!"
}

### Uppdatera note
DELETE {{API_URL}}/login/4